flags: {}
build:
  split-objs: true
packages:
- location: '.'
- location: ../../ghcjs-commonjs
- location:
    git: git@github.com:osener/pandoc
    commit: d3812ef17cf9c27197aac91298832975fde10939
extra-deps:
- SHA-1.6.4.2
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- conduit-1.2.6.6
- data-default-0.5.3
- data-default-class-0.1.1
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.1.1.2
- enclosed-exceptions-1.0.2
- exceptions-0.8.2.1
- lifted-base-0.2.3.6
- mmorph-1.0.6
- monad-control-1.0.1.0
- nats-1.1.1
- network-uri-2.6.1.0
- pandoc-types-1.12.4.7
- parsec-3.1.11
- random-1.1
- resourcet-1.1.7.4
- semigroups-0.18
- tagged-0.8.4
- tagsoup-0.13.10
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- xml-1.3.14
- yaml-0.8.18
resolver: ghcjs-0.2.0.20160414_ghc-7.10.3
